import Head from "next/head";
import Image from "next/image";
import Nav from "../../components/nav/nav";
import React, { useEffect, useState } from "react";
import { useAuth } from "../../lib/auth";
import Cart from "../../components/cart/cart";
import { db } from "../../lib/firebase";
import Link from "next/link";
import router from "next/router";
import {IoMdAdd}  from 'react-icons/io'
import {AiOutlineMinus} from 'react-icons/ai'

import { useSnackbar } from "notistack";

import { PayPalScriptProvider, PayPalButtons } from "@paypal/react-paypal-js";






export async function getServerSideProps(context) {

    let productNo = context.params.product;
    //console.log(context.params.product)

    let id;
    let datas=[];

    var productData= await db
      .collection("Products")
      
      .limit(1)
      .where("Name", "==", productNo)
      .get()
      .then((querySnapshot) => {
        querySnapshot.forEach((doc) => {
            datas.push(doc.data());
            id=doc.id
         
        });
      })
      .catch(function (error) {
        console.log("Error getting that Product: ", error);
      });
  return {
    props: {
        datas,
        productID: id
    }, // will be passed to the page component as props
  }
}



export default function Product({datas, productID}) {
  const { user, userLoading } = useAuth();
  const [loading, setLoading] = useState(false);
  const [cartVisible, setCartVisible] = useState(false);
  const [quantity, setQuantity] = useState(1);
  const [totalPrice, setTotalPrice] = useState(datas[0].price);
  let incrementCounter = () => setQuantity(quantity + 1);
  let decrementCounter = () => setQuantity(quantity - 1);

  const { enqueueSnackbar, closeSnackbar } = useSnackbar();


  
  const auth = useAuth();

  
  return (
    <div className="">
      <Head>
        <title>{datas[0].Name} | Varalhub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" href="icons/apple-icon-180.png" />

        <meta name="apple-mobile-web-app-capable" content="yes"></meta>

        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-2048-2732.jpg"
          media="(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-2732-2048.jpg"
          media="(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-1668-2388.jpg"
          media="(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-2388-1668.jpg"
          media="(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-1536-2048.jpg"
          media="(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-2048-1536.jpg"
          media="(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-1668-2224.jpg"
          media="(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-2224-1668.jpg"
          media="(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-1620-2160.jpg"
          media="(device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-2160-1620.jpg"
          media="(device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-1284-2778.jpg"
          media="(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-2778-1284.jpg"
          media="(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-1170-2532.jpg"
          media="(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-2532-1170.jpg"
          media="(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-1125-2436.jpg"
          media="(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-2436-1125.jpg"
          media="(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-1242-2688.jpg"
          media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-2688-1242.jpg"
          media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-828-1792.jpg"
          media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-1792-828.jpg"
          media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-1242-2208.jpg"
          media="(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-2208-1242.jpg"
          media="(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-750-1334.jpg"
          media="(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-1334-750.jpg"
          media="(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-640-1136.jpg"
          media="(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-1136-640.jpg"
          media="(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)"
        />

<script
              dangerouslySetInnerHTML={{
                __html: `
              if (document.cookie && document.cookie.includes('fast-auth')) {
                
              }else{
                window.location.href = "/login"
              }
            `
              }}
            />

{/* <script defer src="https://www.paypal.com/sdk/js?client-id=AUm6BpDE_B2jakOal0JD2-Beyuob80RbA6o2aUZnmdKKJZq5_9vtSnk0sDGi5Upq-m6ChrkU3PC56Vz8"></script> */}
      </Head>

      <Nav user={auth.user}  setCartVisible={setCartVisible} isCheckout={false} />

      <main className="">
        <div className=" flex flex-col px-20 py-8 ">
          <div className=" flex flex-col space-y-3">
            <span className=" font-bold text-gray-900  text-2xl">
              {datas[0].Name}
            </span>
            <div className=" flex flex-row space-x-4  overflow-y-auto">

                <div className="">
                <Image
                          alt={datas[0].Name}
                          className=" h-full w-full"
                          src={datas[0].photoUrl}
                          width={400}
                          height={300}
                        ></Image>
                </div>

                <div className=" flex flex-col w-1/4 space-y-1">

                    <span>
                        {datas[0].Description}
                    </span>
                    <span className="font-bold text-blue-600">
                        USD {datas[0].price.toString()}
                    </span>

                    <div className=" flex flex-row w-24 justify-between px-2 bg-green-50 rounded-md h-10 items-center">
                        <div
                        onClick={()=>{
                            if(quantity > 1){
                                decrementCounter();
                                setTotalPrice(quantity* datas[0].price);
                               
                            }
                        }}
                        className=" cursor-pointer ">
                            <AiOutlineMinus/>
                        </div>
                        <div className="">{quantity}</div>
                        <div
                        onClick={()=>{
                            if(quantity<= datas[0].Quantity && quantity>0){
                                incrementCounter();
                                setTotalPrice(quantity* datas[0].price);

                               
                            }
                        }}
                        className=" cursor-pointer ">
                            <IoMdAdd/>
                        </div>
                    </div>

                    
                    <div className=" flex flex-col space-y-2 ">

                        <div className=" w-full">

                            <button
                            onClick={()=>{
                                db
    .collection("Cart")
    .doc(auth.user.uid)
    .collection("Items")
    .doc(productID)
    .set({Description: datas[0].Description,
    Name: datas[0].Name,
    Quantity: quantity,
    photoUrl: datas[0].photoUrl,
    price: datas[0].price,
    rating: datas[0].rating,
    maxSelect: datas[0].Quantity
    }, { merge: true }).then(()=>{
        enqueueSnackbar("Added to Cart", {
            anchorOrigin: {
              vertical: "bottom",
              horizontal: "center",
            },
            variant: "success",
          });

          setCartVisible(true)
    });
                            }}
                            className="rounded-md py-3 w-full bg-blue-500 text-gray-50 font-bold">Add to cart</button>

                        </div>


                    <PayPalScriptProvider options={{ "client-id": "AUm6BpDE_B2jakOal0JD2-Beyuob80RbA6o2aUZnmdKKJZq5_9vtSnk0sDGi5Upq-m6ChrkU3PC56Vz8" }}>
            <PayPalButtons style={{ layout: "horizontal" }} createOrder={(data, actions) => {
                return actions.order.create({
                    purchase_units: [
                      {
                        description: datas[0].Name,
                        amount: {
                          value: totalPrice.toString(),
                        },
                      },
                    ],
                  });
            }}
            
            onApprove={(data, actions)=> {

                enqueueSnackbar("Item purchased successfully", {
                    anchorOrigin: {
                      vertical: "bottom",
                      horizontal: "center",
                    },
                    variant: "success",
                  });
                return actions.order.capture();
              }
            }
            
            />
        </PayPalScriptProvider>
                    </div>

                </div>
             
            </div>
          </div>
        </div>

        {cartVisible ? <Cart  setCartVisible={setCartVisible} user={auth.user} /> : null}
      </main>
    </div>
  );
}
