import React, {useState, useEffect}  from 'react'
import Nav from "../components/nav/nav";
import { useAuth } from "../lib/auth";
import Image from 'next/image'
import {db } from '../lib/firebase'
import { PayPalScriptProvider, PayPalButtons } from "@paypal/react-paypal-js";
import { useSnackbar } from "notistack";
import Head from "next/head";


function Checkout() {

    const [cartVisible, setCartVisible] = useState(false);
    const [empty, setEmpty] = useState(false);
    const [items, setItems]= useState([]);
    const auth = useAuth();
    const { enqueueSnackbar, closeSnackbar } = useSnackbar();

    const [total , setTotal]= useState(0)

    


    useEffect(()=>{
        if(auth.user!=null){
            
            db.collection("Cart").doc(auth.user.uid).collection("Items").onSnapshot((snapshot)=>{

                if(snapshot.size===0){

                    setEmpty(true)
                }else{
                    setTotal(0)
                    setEmpty(false)
                }
    
                const newItems=snapshot.docs.map((doc)=>({
                    id: doc.id,
                    ...doc.data()
                }))

                newItems.map((item)=>{

                   
                   setTotal( (item.Quantity * item.price))
                })
    
                setItems(newItems);
    
            })
        }

    

    }, [])


    // console.log(total);
       


    return (

        <div className="">



<Head>
        <title>Checkout | Varalhub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" href="icons/apple-icon-180.png" />

        <meta name="apple-mobile-web-app-capable" content="yes"></meta>

        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-2048-2732.jpg"
          media="(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-2732-2048.jpg"
          media="(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-1668-2388.jpg"
          media="(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-2388-1668.jpg"
          media="(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-1536-2048.jpg"
          media="(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-2048-1536.jpg"
          media="(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-1668-2224.jpg"
          media="(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-2224-1668.jpg"
          media="(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-1620-2160.jpg"
          media="(device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-2160-1620.jpg"
          media="(device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-1284-2778.jpg"
          media="(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-2778-1284.jpg"
          media="(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-1170-2532.jpg"
          media="(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-2532-1170.jpg"
          media="(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-1125-2436.jpg"
          media="(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-2436-1125.jpg"
          media="(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-1242-2688.jpg"
          media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-2688-1242.jpg"
          media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-828-1792.jpg"
          media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-1792-828.jpg"
          media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-1242-2208.jpg"
          media="(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-2208-1242.jpg"
          media="(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-750-1334.jpg"
          media="(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-1334-750.jpg"
          media="(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-640-1136.jpg"
          media="(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
        />
        <link
          rel="apple-touch-startup-image"
          href="icons/apple-splash-1136-640.jpg"
          media="(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)"
        />

<script
              dangerouslySetInnerHTML={{
                __html: `
              if (document.cookie && document.cookie.includes('fast-auth')) {
                
              }else{
                window.location.href = "/login"
              }
            `
              }}
            />

{/* <script defer src="https://www.paypal.com/sdk/js?client-id=AUm6BpDE_B2jakOal0JD2-Beyuob80RbA6o2aUZnmdKKJZq5_9vtSnk0sDGi5Upq-m6ChrkU3PC56Vz8"></script> */}
      </Head>
        

        <Nav user={auth.user}  setCartVisible={setCartVisible} isCheckout={true} />

        <main className=" flex flex-col px-20 py-4 space-y-2">

            <h1 className=" text-gray-900 text-3xl font-bold">Checkout</h1>

            <div className=" w-3/5">
            {
              items.map((item)=>{
                  return(
                    <div key={item.id} className=" h-24 border border-gray-100 shadow w-full rounded flex flex-row">
                    <div className=" rounded-md  h-full bg-red-50 w-2/12">
                    <Image
                          alt={item.Name}
                          className=" h-full w-full"
                          src={item.photoUrl}
                          width={120}
                          height={90}
                        ></Image>
                    </div>
                    <div className=" flex-1 w-1/5 flex-col px-2 py-2">

                        
                        
                    <p className="truncate w-full max-w-lg">{item.Name}</p>
                        <div className=" flex flex-row space-x-1 items-baseline">
                        {/* <span className=" text-sm">
                            {item.Quantity} X
                        
                        </span> */}
                        <span>USD {(item.price* item.Quantity).toString()}</span> 
                        </div>
                       
                    </div>
                    
                  </div>
                  )
              })
          }
            </div>

            <div className=" flex flex-row space-x-2">
                <h1 className=" text-gray-700 font-medium">Total</h1>
            <span className="  font-semibold ">USD {total}</span>
            </div>

            <div className=" w-2/5 pt-5">
            <PayPalScriptProvider options={{ "client-id": "AUm6BpDE_B2jakOal0JD2-Beyuob80RbA6o2aUZnmdKKJZq5_9vtSnk0sDGi5Upq-m6ChrkU3PC56Vz8" }}>
            <PayPalButtons style={{ layout: "horizontal" }} createOrder={(data, actions) => {
                return actions.order.create({
                    purchase_units: [
                      {
                        amount: {
                          value: "25",
                        },
                      },
                    ],
                  });
            }}
            
            onApprove={(data, actions)=> {

                enqueueSnackbar("Item purchased successfully", {
                    anchorOrigin: {
                      vertical: "bottom",
                      horizontal: "center",
                    },
                    variant: "success",
                  });
                return actions.order.capture();
              }
            }
            
            />
        </PayPalScriptProvider>
            </div>



        </main>

        </div>
    )
}

export default Checkout
