import React, { useState } from "react";
import firebase from "firebase/app";
import { useRouter } from "next/router";
import Link from "next/link";
import Head from "next/head";
import { useSnackbar } from "notistack";
import { useAuth } from "../lib/auth";

function Login() {
  const router = useRouter();
  const [email, setEmail] = useState("");
  const [pass, setPass] = useState("");

  const [loading, setLoading] = useState(false);
  const { signinWithEmail } = useAuth();
  const auth = useAuth();

  const { enqueueSnackbar, closeSnackbar } = useSnackbar();

  const onLogin = (email, pass) => {
    setLoading(true);
    signinWithEmail(email, pass).catch((error) => {
      setLoading(false);
      enqueueSnackbar(error.message, {
        anchorOrigin: {
          vertical: "bottom",
          horizontal: "center",
        },
        variant: "error",
      });
    });
  };
  return (
    <>
      <Head>
        <title>Login to Merchant dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <script
              dangerouslySetInnerHTML={{
                __html: `
              if (document.cookie && document.cookie.includes('fast-auth')) {
                window.location.href = "/dashboard"
              }
            `
              }}
            /> */}
      </Head>

      <nav className="lg:h-20 h-16 px-4  lg:px-20 flex items-center relative">
        <div className="">
          <Link href="/" passHref={true}>
            <span className="font-bold text-2xl lg:text-3xl text-gray-800 cursor-pointer">
              BlueBasket
            </span>
          </Link>
        </div>
        {!auth.user ? (
          <div className=" absolute right-0 mr-4 lg:mr-20 flex flex-row space-x-4">
            <Link href="/signup" passHref={true}>
              <button className="bg-blue-600 rounded-md  text-sm lg:text-base text-gray-50 py-2 px-6 font-medium hover:bg-blue-700 hover:shadow">
                Sign up{" "}
              </button>
            </Link>
          </div>
        ) : (
          <div className=" absolute right-0 mr-4 lg:mr-20 flex flex-row items-center space-x-5">
            <Link href="/dashboard" passHref={true}>
              <div className=" h-10 w-10 rounded-md bg-red-100 cursor-pointer"></div>
            </Link>

            <button
              onClick={async () => {
                await firebase.auth().signOut();
                router.push("/");
              }}
              className="bg-blue-50 text-sm lg:text-base  rounded-md text-blue-700 py-2 px-6 font-medium"
            >
              Log out
            </button>
          </div>
        )}
      </nav>

      <main className=" w-full h-screen bg-gray-50 flex items-start lg:items-center justify-center">
        <form
          onSubmit={async (e) => {
            e.preventDefault();
            onLogin(email, pass);
          }}
          className="flex flex-col space-y-6  mt-20 lg:mt-0  lg:mb-20 bg-white shadow-sm px-8 w-11/12 lg:w-4/12 relative py-10"
        >
          <h1 className="font-medium text-2xl lg:text-xl">
            Login to Vahalhub
          </h1>
          <input
            onChange={(e) => setEmail(e.target.value)}
            className="rounded-md py-3 px-4 outline-none border focus:border-blue-600 "
            type="email"
            required
            placeholder="Email"
          ></input>
          <input
            onChange={(e) => setPass(e.target.value)}
            className="rounded-md py-3 px-4  outline-none border focus:border-blue-600"
            type="password"
            required
            placeholder="Password"
          ></input>

          <button
            className=" rounded-md font-medium bg-blue-700 text-gray-50  px-12  py-3 outline-none hover:bg-blue-800 hover:shadow"
            type="submit"
          >
            Login
          </button>
          
        </form>
      </main>
    </>
  );
}

export default Login;
